<?php

/**
 * PluginpeanutPostsPeanutCategoriesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginpeanutPostsPeanutCategoriesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginpeanutPostsPeanutCategoriesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginpeanutPostsPeanutCategories');
    }
}