generator:
  class: sfDoctrineGenerator
  param:
    model_class:           tag
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          tag
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        sort:     [name, asc]
        display:  [name]
        
      filter:
        display:  [name]
      form:    ~
      edit:    ~
      new:     ~
