peanutCategories:
  actAs:
    Sluggable:
      fields: [name]
    NestedSet:
      hasManyRoots: true
      rootColumnName: root_id
  columns:
    id:
      primary: true
      type: integer
      autoincrement: true
    name:
      type: string(255)
      notnull: true
    description:
      type: clob
peanutPosts:
  actAs:
    Sluggable:
      fields: [title]
    Timestampable: 
    Taggable: 
  columns:
    id:
      primary: true
      type: integer
      autoincrement: true
    title:
      type: string(255)
      notnull: true
    content:
      type: clob
      notnull: true
    excerpt:
      type: clob
    category:
      type: integer
      notnull: true
    status:
      default: draft
      type: string
      notnull: true
      values: [draft,publish]
    author:
      type: integer
  relations:
    peanutCategories:
      foreignAlias: postCategory
      local: category
      foreign: id
    sfGuardUser:
      local: author
      foreign: id