peanutCategories:
  actAs:
    Sluggable:
      fields: [name]
    NestedSet:
      hasManyRoots: true
      rootColumnName: root_id
  columns:
    id:
      primary: true
      type: integer
      autoincrement: true
    name:
      type: string(255)
      notnull: true
    description:
      type: clob
      
peanutPosts:
  actAs:
    Sluggable:
      fields: [title]
    Timestampable: 
    Taggable: 
  columns:
    id:
      primary: true
      type: integer
      autoincrement: true
    title:
      type: string(255)
      notnull: true
    content:
      type: clob
      notnull: true
    excerpt:
      type: clob
    status:
      default: draft
      type: string
      notnull: true
      values: [draft,publish]
    author:
      type: integer
  relations:
    peanutCategories:
      refClass: peanutPostsPeanutCategories
      local: peanut_post_id
      foreign: peanut_categories_id
    sfGuardUser:
      local: author
      foreign: id
      
peanutPostsPeanutCategories:
  columns:
    peanut_post_id:
      type: integer
      primary: true
    peanut_categories_id:
      type: integer
      primary: true
  relations:
    peanutPosts:
      local: peanut_post_id
      foreignAlias: peanutCategory
      onDelete: cascade
    peanutCategories:
      local: peanut_categories_id
      foreignAlias: peanutCategory
      onDelete: cascade